[package]
name = "cddns"
description = "A modern, hackable, green DDNS CLI and service for Cloudflare."
authors = ["Spencer C. Imbleau <spencer@imbleau.com>"]
version = "0.2.3"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/simbleau/cddns"
readme = "README.md"
keywords = ["cloudflare", "ddns", "dns"]
categories = ["command-line-utilities", "network-programming"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.29", features = ["derive", "env"] }
tokio = { version = "1.23.0", features = ["full"] }
crossterm = "0.25.0"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
ansi_term = "0.12.1"
reqwest = { version = "0.11.13", features = ["json"] }
toml = "0.5.9"
anyhow = "1.0.66"
envy = "0.4"
serde = { version = "1.0.150", features = ["derive"] }
serde_json = "1.0.89"
serde_yaml = "0.9.14"
ron = "0.8"
regex = "1.7.0"
public-ip = "0.2.2"
directories = "4.0.1"
chrono = "0.4.23"
