[package]
name = "cfddns"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.18", features = ["derive", "env"] }
tokio = { version = "1.21.2", default-features = false, features = ["full"] }
toml = "0.5.9"
anyhow = "1.0.66"
envy = "0.4"
serde = { version = "1.0.147", features = ["derive"] }