# This is an example config file for cddns.
#
# cddns uses the typical layered approach. The config file is the base, which
# is superseded by environment variables, which are superseded by CLI flags.
#
# With the CLI installed, you can use `cddns config build` to interactively
# build this TOML file.

[verify]
# The API Token with permission to Edit DNS Zones.
# Read more: https://dash.cloudflare.com/profile/api-tokens
token = "<YOUR_CLOUDFLARE_TOKEN>"

[list]
# Zones (domains, subdomains, identities) to include with `cfddns list`.
include_zones = [".*"] # Default: [".*"]
# Zones (domains, subdomains, identities) to ignore with `cfddns list`.
ignore_zones = [] # Default: []
# (DNS) Records to include with `cfddns list`.
include_records = [".*"] # Default: [".*"]
# (DNS) Records to ignore with `cfddns list`.
ignore_records = [] # Default: []

[inventory]
# The path to your inventory file.
path = "inventory.yaml" # Default: "inventory.yaml"
# Skip prompts asking to update outdated DNS records.
force_update = false # Default: false
# Skip prompts asking to prune invalid DNS records.
force_prune = false # Default: false
# The interval for refreshing inventory records in milliseconds.
interval = 60000 # Default: 30000 (30s)